version: "3.9"
services:
  redis:
    container_name: hitc_redis
    image: "redis:6.2.1-alpine"
    ports:
      - 6379:6379
    volumes:
      - ./data:/sampledata
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
